--- Client-side packet IDs for Bancho protocol.
---@class bancho.protocol.ClientPackets
local M = {}
M.CHANGE_ACTION = 0
M.SEND_PUBLIC_MESSAGE = 1
M.LOGOUT = 2
M.REQUEST_STATUS_UPDATE = 3
M.PING = 4
M.START_SPECTATING = 16
M.STOP_SPECTATING = 17
M.SPECTATE_FRAMES = 18
M.CREATE_MATCH = 31
M.JOIN_MATCH = 32
M.PART_MATCH = 33
M.MATCH_READY = 39
M.MATCH_START = 44
M.MATCH_SCORE_UPDATE = 47
M.MATCH_COMPLETE = 49
M.CHANNEL_JOIN = 63
M.CHANNEL_PART = 78
return M
