#!/bin/bash
rm -f luacov.stats.out
cd "$(dirname "$0")"
export LD_LIBRARY_PATH="${LD_LIBRARY_PATH:+$LD_LIBRARY_PATH:}/usr/lib:$PWD/bin/linux64"
APPIMAGE_EXTRACT_AND_RUN=1 ./bin/linux64/love-11.5-x86_64.AppImage . test "$@"
