#!/bin/bash
# Limit virtual memory to 2GB to prevent runaway test scripts from consuming all RAM
ulimit -v 2097152

rm -f luacov.stats.out
cd "$(dirname "$0")"
source ./aqua/env/luajit_setenv
export LD_LIBRARY_PATH="${LD_LIBRARY_PATH:+$LD_LIBRARY_PATH:}/usr/lib:$PWD/bin/linux64"
luajit test_resty.lua "$@"
